### ISSUE TITLE
Mouse/keyboard Pro @ Android 12

### ISSUE THREAD

**Issue by Fun2mass** [dysquard/pgpa#112]
Hi.
Will you update app for A12?

Last night my Samsung S10+ updated to A12, and now touchscreen aren't work if I launch game with Panda app launched.

And yes, I saw solution for gamepad, but as it said in that thread- it helps only with mouse clicks.

Thanks

**Comment by Xwicked-knightX** [comment]
The activator has been updated for android 12, 6 hours after your post! Download the activator again and try again.

**Comment by Fun2mass** [comment]
> The activator has been updated for android 12, 6 hours after your post! Download the activator again and try again.

Thanks, but it seems like it goes with same code as suggested in other thread about Gamepad version. Just try it(new activator) but only mouse works, keyboard not

**Comment by Xwicked-knightX** [comment]
If you have the previous version delete it and download it from https://github.com/dysquard/pgpa/releases/tag/112
Thats the latest download link, i have a Galaxy S21 ultra and this download made everything start working for me for the first time since i got the phone a year ago.

**Comment by Fun2mass** [comment]
> If you have the previous version delete it and download it from https://github.com/dysquard/pgpa/releases/tag/112 Thats the latest download link, i have a Galaxy S21 ultra and this download made everything start working for me for the first time since i got the phone a year ago.

You're right! Also i'he download activator from wrong url.
Now it's work. Thank you!

**Comment by iamSlightlyWind** [comment]
The activator doesnt seem to be working for me on oneui 4.1, android 12 tab s7. The mouse and mouse buttons do work, but keyboard input seems to be directed to the opening app/game rather than panda (or instead, pressing the mapped button without any assigned key, which is colored red with a question mark?). The keyboard is an external keyboard connected through usb, which previously works perfectly on android 11. If anyone has a solution, please let me know!
